language: java

jdk:
  - openjdk7
  - oraclejdk7  
  - oraclejdk8

before_install: git clone https://github.com/checkstyle/checkstyle.git && cd checkstyle 
  && mvn clean install -DskipTests -Dlinkcheck.skip=true -Dmaven.javadoc.skip=true 
        -Dpmd.skip=true -Dfindbugs.skip=true -Dcobertura.skip=true 
  && cd ..

install: mvn clean test

